- name: generate self-signed ssl certificates 
  include_role:
    name: install-configure-vault
    tasks_from: generate-cert
  vars:
    ssl_subject: "{{ cert_ssl_subject }}"
    certs_copy_target: "{{ cert_mount_target }}"
    key_name: "{{ cert_key_name }}"
    crt_name: "{{ cert_crt_name }}"
    remote_src: "{{ cert_remote_src }}"
  tags: certs