---
- name: Generate self-signed ssl certificates
  ansible.builtin.include_role:
    name: generate-selfsigned-certs
  vars:
    ssl_subject: "{{ cert_ssl_subject }}"
    ssl_ip: "{{ cert_ssl_ip }}"
    certs_copy_target: "{{ cert_mount_target }}"
    key_name: "{{ cert_key_name }}"
    crt_name: "{{ cert_crt_name }}"
    remote_src: "{{ cert_remote_src }}"
  tags: certs
