- name: Install python requirements
  include_role:
    name: install-requirements
  vars:
    update_packages: false
    python_modules: "{{ podman_python_modules }}"
  tags: setup

- name: Make sure podman is installed
  include_role:
    name: install-configure-podman
  tags: setup


