- name: Install python requirements
  include_role:
    name: install-requirements
  vars:
    update_packages: false
    python_modules: "{{ podman_python_modules }}"
  tags: setup

- name: Make sure podman is installed
  include_role:
    name: install-configure-podman
  tags: setup

- name: Calculate list of ports to launch container
  vars:
    current_port: "{{ item.value.host }}:{{ item.value.container }}"
  set_fact:
    port_list: "{{ port_list | default([]) + [current_port] }}"
  loop: "{{ lookup('dict', ports, wantlist=True) }}"
  when: ports is defined and ports.values()|length > 0

- name: Set ports to null if no ports are given
  set_fact:
    port_list: null
  when: ports is defined and ports.values()|length <= 0

- name: Calculate list of env_vars to launch container
  set_fact:
    env_vars_dict: "{{ env_vars_dict|default({}) | combine( {item.value.key | upper: item.value.value} ) }}"
  loop: "{{ lookup('dict', env_vars, wantlist=True) }}"

- name: Set env_vars_dict to null if no env vars are given
  set_fact:
    env_vars_dict: null
  when: env_vars is defined and env_vars.values()|length <= 0

- name: create local mount dirs (if defined)
  tags: mounts
  file:
    path: "{{ item.value.host | dirname }}"
    state: directory
    recurse: yes
  loop: "{{ lookup('dict', mounts, wantlist=True) }}"
  when: mounts is defined

- name: "Allow conatiner to modify files in mount dirs"
  sefcontext:
    target: "{{  item.value.host | dirname }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  loop: "{{ lookup('dict', mounts, wantlist=True) }}"
  when: mounts is defined

- name: "Apply new SELinux file context to mount dirs"
  command: "restorecon -Rv {{ item.value.host | dirname }}"
  loop: "{{ lookup('dict', mounts, wantlist=True) }}"
  when: mounts is defined

- name: ensure container's exposed ports firewall state
  tags: firewall
  firewalld:
    port: "{{ item.value.host }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ lookup('dict', ports, wantlist=True) }}"
  when: ports is defined