---
- name: Stop existing service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: true
    state: stopped
    daemon_reload: true

- name: Remove cid, pid and service files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ cidfile }}"
    - "{{ pidfile }}"
    - "{{ service_files_dir }}/{{ service_name }}"

- name: Remove (may) existing local mount dirs
  tags: mounts
  ansible.builtin.file:
    path: "{{ item.value.host | dirname }}"
    state: directory
    recurse: true
  loop: "{{ lookup('dict', mounts, wantlist=True) }}"
  when: mounts is defined
