- name: pull container image
  podman_image:
    name: "{{ container_image }}"

- name: Run container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    state: "{{ state }}"
    recreate: "{{ recreate }}"
    ports: "{{ port_list }}"
    env: "{{ env_vars_dict }}" 