---
- name: Run container (if the container should be running permanently - it will be stopped and restarted in a systemd service)
  containers.podman.podman_container:
    name: "{{ container_name }}"
    pod: "{{ pod_name }}"
    image: "{{ container_image }}"
    state: "{{ state }}"
    recreate: "{{ recreate }}"
    env: "{{ env_vars_dict }}" 
    ports: "{{ port_list }}"
    volumes: "{{ mount_list }}"

- name: "Gather info about pod {{ pod_name }}"
  containers.podman.podman_pod_info:
    name: "{{ pod_name }}"

- name: "Gather info about container {{ container_name }}"
  containers.podman.podman_container_info:
    name: "{{ container_name }}"