roles:
- src: git@codehub.sva.de:Lab/stuttgart-things/ansible/install-configure-podman.git
  scm: git
- src: git@codehub.sva.de:Lab/stuttgart-things/kubernetes/deploy-podman-container.git
  scm: git
- src: git@codehub.sva.de:Lab/stuttgart-things/supporting-roles/install-requirements.git
  scm: git
  
collections:
- name: containers.podman 
