---
# handlers file for deploy-podman-container
- name: Reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
